NUM_OF_FIREFLIES = 40
MAX_GENERATIONS = 200

ALPHA = 0.7		
BETAMIN = 0.2        
GAMMA = 1.0	

MAX_CPU = 512
MAX_MEM = 2048

NUM_OF_REQUESTS = 200
DIMENSION = NUM_OF_REQUESTS
MAX_NUM_OF_NODES = 15
NUM_OF_NODES = 64
NUM_OF_DCS = 10
SCALE = 3

PERFECT_SCORE = 0.8

upperBound = [None] * DIMENSION
lowerBound = [None] * DIMENSION